"""Capture the interactive Rich review panel for one question.

The committed `review_*.log` files are line-oriented summaries written by
`workflow._review_log`. The actual reviewer panel (`review._render_review_panel`)
is much richer: Key Facts table, Derivation candidates table, structured
why_chosen panel, syntax-highlighted SQL, Layer A/B/C tables, FLAGS-vs-
HYPOTHESIS summary. This script renders that panel for Q1 and writes the
text export to `outputs/sample/review_panel_rendered.txt` so evaluators can
see what a human reviewer actually sees during the pause step.

Q1 was chosen because its Layer B disagreement (~+13.71% vs mart_ops_dashboard)
exercises the FLAGS + HYPOTHESIS rendering.

Run:
    PYTHONPATH=src python scripts/render_review_panel.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from rich.console import Console

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from pluang_agent import review as review_mod  # noqa: E402
from pluang_agent.models import PipelineItem, QualityReport, SQLAgentAnswer  # noqa: E402


def _load_by_id(path: Path, qid: str) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    for entry in payload:
        if entry.get("question_id") == qid:
            return entry
    raise KeyError(f"question_id={qid!r} not found in {path}")


def main() -> int:
    sample = REPO / "outputs" / "sample"
    qid = "q1_gtv_idr_by_asset_oct_2025"

    plan_json = _load_by_id(sample / "question_plans.json", qid)
    answer_json = _load_by_id(sample / "sql_agent_answers.json", qid)
    qa_json = _load_by_id(sample / "quality_report.json", qid)

    # Re-hydrate Pydantic models from the committed JSON.
    from pluang_agent.models import BusinessQuestion, QuestionPlan

    plan = QuestionPlan.model_validate(plan_json)
    answer = SQLAgentAnswer.model_validate(answer_json)
    qa = QualityReport.model_validate(qa_json)
    question = BusinessQuestion(
        id=qid,
        text="What was total GTV (IDR) by asset class in October 2025?",
        metric="gtv_idr_by_asset_class",
        period="October 2025",
    )
    item = PipelineItem(
        question=question,
        question_plan=plan,
        answer=answer,
        quality_report=qa,
    )

    # Recording console — wide width so tables don't wrap awkwardly.
    recorder = Console(record=True, width=140)
    original = review_mod.console
    review_mod.console = recorder  # type: ignore[assignment]
    try:
        review_mod._render_review_panel(item)
    finally:
        review_mod.console = original  # type: ignore[assignment]

    out = sample / "review_panel_rendered.txt"
    header = (
        "# Captured interactive review panel for Q1 (the richest Layer B disagreement).\n"
        "# Generated by scripts/render_review_panel.py from the committed sample JSONs.\n"
        "# This is what a human reviewer sees during the pause step — not the\n"
        "# line-oriented summary in review_approval.log / review_rejection_*.log.\n"
        "#\n"
        "# Sections in order: Key Facts → Derivation candidates → why_chosen (key:value)\n"
        "#   → question header + trust profile → Source → Answer → SQL\n"
        "#   → QA Summary (FLAGS vs HYPOTHESIS) → Layer A FLAGS → Layer B FLAGS + HYPOTHESIS.\n"
        "\n"
    )
    out.write_text(header + recorder.export_text(), encoding="utf-8")
    print(f"Wrote {out} ({out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
